# Nota: VocÊ pode criar um arquivo na pasta langs com o nome (ex: pt-br.json) para adicionar novas traduções ou para alterar uma tradução existente.

langs = {
    "en-us": {
        "stream": "Live",
        "loop_text": "Looping",
        "loop_queue": "Loop: Queue",
        "loop_remaining": "track loops",
        "paused": "Paused",
        "view_music": "Watch/Listen Online",
        "listen_along": "Listen along on Discord",
        "author": "By",
        "playlist": "Playlist",
        "view_playlist": "View Playlist",
        "album": "Album",
        "view_album": "View Album",
        "idle": ["Idling...", "   "],
        "invite": "Invite",
        "support_server": "Support Server",
        "queue": "Queue: {queue}",
    },
    "pt-br": {
        "stream": "Ao vivo",
        "loop_text": "Repetição ativada",
        "loop_queue": "Repetição da fila: ativada",
        "loop_remaining": "Repetições restantes",
        "paused": "Em pausa",
        "view_music": "Ouvir Online",
        "listen_along": "Ouvir junto via Discord",
        "author": "Por",
        "playlist": "",
        "view_playlist": "Ver Playlist",
        "album": "Álbum",
        "view_album": "Ver Álbum",
        "idle": ["Aguardando por", "novas músicas..."],
        "invite": "Me adicione no seu server.",
        "support_server": "Servidor de Suporte",
        "queue": "Na fila: {queue}",
    }
}