# Nota: VocÊ pode criar um arquivo na pasta langs com o nome (ex: pt-br.json) para adicionar novas traduções ou para alterar uma tradução existente.

langs = {
    "en-us": {
        "stream": "Live",
        "loop_text": "Looping",
        "loop_queue": "Loop: Queue",
        "loop_remaining": "Remaining plays",
        "playing": "Playing...",
        "paused": "Paused",
        "listen_music": "Listen (Browser/App)",
        "listen_on": "Listen on",
        "listen_along": "Listen along (Voice Channel)",
        "recommended": "Recommended",
        "server": "Server",
        "author": "By",
        "playlist": "Playlist",
        "view_playlist": "View Playlist",
        "album": "Album",
        "idle": ["I'm currently not playing anything...", "waiting for more songs"],
        "invite": "Add Bot",
        "support_server": "Support Server",
        "queue": "Queue: {queue}",
    },
    "pt-br": {
        "stream": "Ao vivo",
        "loop_text": "Repetição ativada",
        "loop_queue": "Repetição: Lista",
        "loop_remaining": "Repetições restantes",
        "playing": "Tocando",
        "paused": "Em pausa",
        "listen_music": "Ouvir no navegador/app",
        "listen_on": "Ouvir no",
        "listen_along": "Ouvir junto no canal de voz",
        "recommended": "Recomendada",
        "server": "Servidor",
        "author": "Por",
        "playlist": "Playlist",
        "view_playlist": "Visualizar playlist",
        "album": "Álbum",
        "idle": ["Não estou tocando algo no momento...", "Aguardando por novas músicas."],
        "invite": "Me adicione no seu servidor",
        "support_server": "Servidor de Suporte",
        "queue": "Na lista: {queue}",
    }
}
